// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "LogKeyValue.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class LogKeyValueHandler : virtual public LogKeyValueIf {
 public:
  LogKeyValueHandler() {
    // Your initialization goes here
  }

  void Put(Response& _return, const std::string& key, const std::string& value) {
    // Your implementation goes here
    printf("Put\n");
  }

  void Get(Response& _return, const std::string& key) {
    // Your implementation goes here
    printf("Get\n");
  }

  void Delete(Response& _return, const std::string& key) {
    // Your implementation goes here
    printf("Delete\n");
  }

  void Exist(Response& _return, const std::string& key) {
    // Your implementation goes here
    printf("Exist\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<LogKeyValueHandler> handler(new LogKeyValueHandler());
  ::std::shared_ptr<TProcessor> processor(new LogKeyValueProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

